/*****************************************************************************
   Project: CEDAR Logic Simulator

   EmbeddedRes: the resources the app cannot start without, compiled in.

   The gate library and the toolbar icons live inside the executable, so nothing
   at runtime has to work out where the program was installed -- a question with
   no good answer for a build run in place. Files that only matter once the app
   is up (the help book) stay on disk.

   Names are paths under res/, e.g. "cl_gatedefs.xml" or "icons/new.svg". The
   table is generated by cmake/module/EmbedResources.cmake.
*****************************************************************************/

#pragma once

#include <cstddef>
#include <string>

namespace cl {
namespace res {

struct Blob {
	const unsigned char* data;
	std::size_t size;
	bool ok() const { return data != nullptr; }
};

// The named resource, or an empty blob if there is no such name.
Blob find(const char* name);

// The named resource as text, or an empty string if there is no such name.
std::string text(const char* name);

}  // namespace res
}  // namespace cl
